### ISSUE TITLE
Complete migration of validate_states to kadi

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi#272]
There are a number of items that need to done to complete the migration from [validate_states](https://github.com/sot/validate_states) to kadi validate_states:

### Tasks
- [x] https://github.com/sot/kadi/pull/269
- [x] Add daily cron job to `aca@kady` cron jobs
- [x] Update AspectCronJobs TWiki
- [x] https://github.com/sot/ska_sun/pull/25
- [x] https://github.com/sot/ska_sun/pull/24
- [x] https://github.com/orgs/sot/projects/16
- [x] https://github.com/sot/jobwatch/issues/59
- [x] Remove Ska `validate_states` cron job and update AspectCronJobs TWiki

**Comment by jeanconn** [comment]
I don't know what the "number of items" are for this issue at this point.

**Comment by taldcroft** [comment]
There was some problem with the tasklist. Check the description again.
